### ISSUE TITLE
Divine Might

### ISSUE THREAD

**Issue by rujind** [EdenServer/community#1121]
1. The TT causes the weird engage bug you get if you engage a mob from on a Chocobo. You auto attack but there's no animation (you can see yourself gaining TP), you cant engage or disengage, and the game thinks you're not engaged so you can use WSs. After the TT dies the bug is gone.
2. Mobs have WAY too high evasion. I have a MUCH easier time hitting land kings and Kirin.
3. The MR spams Perfect Dodge and uses Charm once, it should be the other way around; spam Charm and Perfect Dodge once.
https://ffxiclopedia.fandom.com/wiki/Divine_Might/Strategies

edit:
4. Should Ark Pentasphere disappear from inventory after trading? It's not. I think as long as you don't turn the quest in, you can reuse the same sphere for entry? Not sure what's retail accurate.

**Comment by beitlich** [comment]
Retail the pentasphere did not get removed from your inventory but it could not be used to start the fight again. Similar to testimonies.

**Comment by Setz0r** [comment]
1. haven't been able to reproduce the engage bug, could've been due to packet lag.
2. eva has been fixed
3. MR has been fixed.
4. Pentaspheres remain in inventory but are flagged as used.
5. this ticket is cloooosed

**Comment by godmode** [comment]
Apparently on live this issue still happens. Opening it back up for now.

**Comment by Swift20** [comment]
After running this last night, there seems to be an issue with reraise in the instance as well. 

About 50% of deaths would wipe reraise and some members dead bodies were controllable, sliding along the floor and unable to be raised.

**Comment by AnkleAssassinz** [comment]
-Tractored dead player(s) will pop under the stair/out-of-bound area. 
-Regarding TT: Same issue as unable-to-attack at beginning but I was able to attack it later on when its HP was really low. I remember popping 2hour to kill it asap.

**Comment by Raphtalia1** [comment]
My observations from the other night: 

Its not the TT,  engaging and healing are both bugged until at least one AA dies

We tried MR first, everyone "engaged" but they didnt actually engage, couldn't WS, however everyone saw everyone else auto attacking.

Once the MR died everything behaved as it should, resting was possible, engaging worked normally. TT warped around the stage

Elvaan was insane, Spirits within was doing 2000+ dmg (oneshots tanks), it should only do about 300-500. Evasion was also stupidly high, even with soulvoice songs and food accuracy was a problem
