### ISSUE TITLE
Uncharmed pets retain hate tables

### ISSUE THREAD

**Issue by greyenvy** [EdenServer/community#1214]
When a fighting pet becomes uncharmed, it's hate table on the mob does not reset.  You can recharm it and the mob that should be attacking you then returns to fight your pet again.  This is not how it should work AFAIK.  Hate should be cleared when you lose the pet but is instead retained.

**Comment by godmode** [comment]
@xizeta was this fixed in your BST patch?

**Comment by greyenvy** [comment]
I’ll test this tomorrow and give you an answer.

**Comment by Lexxi-foxxx** [comment]
This is still broken. Noticed it yesterday when a spider uncharmed fighting a beetle. The spider regained hate upon recharming.

**Comment by bkesecker** [comment]
Confirmed, still an issue.

**Comment by 59blargedy** [comment]
resolved in january 11, 2021 patch
