### ISSUE TITLE
Leaving party across server clusters breaks alliance

### ISSUE THREAD

**Issue by Aneyus** [EdenServer/community#1482]
Disbanding your party in a different server cluster will break an alliance. 

E.G. if an alliance is in Dynamis and someone warps out and then drops party, the alliance will break into its component parties. Current workaround for players is to always drop party before leaving event areas.

**Comment by Mikokiko** [comment]
This happen now pretty much whenever someone leave the zone. 

It can do one the following
Break the alliance, 
Break the parties 
Mess up the loot pool

**Comment by Mozzy4Ever** [comment]
This was fixed on the July 19th, 2020 update.
![image](https://user-images.githubusercontent.com/11255886/113517544-2e2ecb00-9546-11eb-91a0-0b3792dc3f50.png)
https://discord.com/channels/482610771126386688/670735434799644690/734448535960813618

**Comment by falzum** [comment]
Something weird is still happening. We had a party leader leave dynamis early and he dropped glass, then did /pcmd leave.

The leader dot moved to someone new but they were unable to invite people and kept getting the 'You are not the party leader' message.

To resolve we had to have everyone /pcmd leave then reform

**Comment by 59blargedy** [comment]
Resolved by party rework in January 19, 2026 update
