### ISSUE TITLE
BASTOK MISSION 2-3

### ISSUE THREAD

**Issue by thorules** [EdenServer/community#2216]
### Checklist

- [X ] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details
Character Beldin on mission 2-3 - talked to Nadij, ran to san doria, spoke to Baraka, Helaka and Halver.  Killed warchief and have the title but when return and talk again to Helaka not CS

**Comment by bkesecker** [comment]
If you haven't called a GM about this via help desk (in-game menu option), please do.  If resolved by GM, please close.  While this behavior is buggy, it isn't a specific bug, rather a known issue with character progression data being saved and affects all players.

**Comment by thorules** [comment]
Raised with GM will close as soon as it is resolved

**Comment by thorules** [comment]
Still not GM if I leave logged in will they be able to sort it or do I need to call GM when I log back in tomorrow ?

**Comment by thorules** [comment]
sorted by GM and thanks all
