### ISSUE TITLE
Summoner AF Weapon not provided by quest

### ISSUE THREAD

**Issue by fluffydeadangel** [EdenServer/community#2526]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

When you turn in the SMN af1 quest for the staff it provides you with a lv 40 bard Horn. To reproduce, turn in the quest "The Puppet Master".

**Comment by fluffydeadangel** [comment]
![image](https://user-images.githubusercontent.com/54287722/76690375-6e00e700-6693-11ea-9427-2405fad69845.png)

**Comment by KnowOne134** [comment]
Issue is fixed

**Comment by Mahou81** [comment]
Definitely not fixed! I had the same issue just now, also received a horn instead of the af wpn.
