### ISSUE TITLE
Attacking Hpemde as they go underwater will cause them to become untargettable

### ISSUE THREAD

**Issue by E5una** [EdenServer/community#2720]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Attack a Hpemde as it is diving back under water to deaggro. It will surface and attack you, but there is no way to target it. I've had to find another monster and sleepga on two separate occasions to escape the untargettable Hpemde.

version 30181205_0

**Comment by 59blargedy** [comment]
i think i forgot to note this in patch notes, but this was resolved in November 29, 2021 update

**Comment by asphodel-eden** [comment]
This is still happening. I RA'd right as the Hpemde went underwater. It became aggressive, but I was unable to target it. I had to zone to lose aggro.
![image](https://user-images.githubusercontent.com/61460959/234907343-0fd6536d-feda-4c1c-b1c5-d21c51968b95.png)
