### ISSUE TITLE
Cannot desynth Hydro Baghnakhs

### ISSUE THREAD

**Issue by baggedmilk2112** [EdenServer/community#3272]
### Checklist

- [ /] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [ /] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [ /] I have provided my client version in the details. (type /ver into your game window)

### Details

https://ffxiclopedia.fandom.com/wiki/Hydro_Baghnakhs?oldid=379747
Cannot desynth Hydro Baghnakhs - says combinations cannot be synthesized. 
30181205_0

**Comment by 59blargedy** [comment]
resolved 11/2 update

**Comment by asphodel-eden** [comment]
Looks like this bug is back. Every time I try the desynthesis of hydro baghnakhs, I get the message "Synthesis canceled. That combination of materials cannot be synthesized."
