### ISSUE TITLE
Om'Yovra (UFO) rose in air and continued to fight

### ISSUE THREAD

**Issue by vrusso-kong** [EdenServer/community#3486]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

Fighting Om'yovra in the Mea area of Al'taieu, one character died, the yovra deaggroed for moment, rose up in the air, aggroed my other character and continued to attack it, while being untargetable. I was duoing and my bard wasn't on the enmity table so I think that might have been the cause. 

SS below showing Yovra in air while continuing to fight.
![img_20201209_175534](https://user-images.githubusercontent.com/20424759/101699155-ad087100-3a48-11eb-94e7-92a294b73593.jpg)
![img_20201209_175539](https://user-images.githubusercontent.com/20424759/101699159-ae399e00-3a48-11eb-8475-afc22b6b5632.jpg)
![img_20201209_175544](https://user-images.githubusercontent.com/20424759/101699160-ae399e00-3a48-11eb-979e-66c55fd6b00a.jpg)
![img_20201209_175546](https://user-images.githubusercontent.com/20424759/101699162-aed23480-3a48-11eb-9724-2b3568ef0c0f.jpg)

**Comment by 59blargedy** [comment]
resolved in November 29, 2021 update

**Comment by dowzer** [comment]
I was fighting a yovra and it rose into the air mid fight, possibly from deaggroing

![img_20230407_131427](https://user-images.githubusercontent.com/54732693/230673884-373349a0-a820-46fa-ae5b-16e16f13351a.jpg)

Continued to fight in the air

![img_20230407_131603](https://user-images.githubusercontent.com/54732693/230674001-b77dd9eb-be00-40e9-a359-929e903446e2.jpg)

**Comment by Slamm21** [comment]
this is still happening, they are deaggroing when you are around 10 yalms away which is definitely wrong.
If you aggrod one of these on retail and could not sleep/kill it you ran to the zone and hoped
https://www.youtube.com/watch?v=vxSrThKyduE
video showing a blm solo, often 20 yalms away no deaggro
