### ISSUE TITLE
Quick Draw Damage Calculation is wrong (Too high)

### ISSUE THREAD

**Issue by VirtuosusFFXI** [EdenServer/community#4427]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [x] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [x] I have provided my client version in the details. (type /ver into your game window)

### Details

version 30181205_0

Tested on East Ronfaure rabbits, using the following formula from Chen's Corsair Dossier:
`floor[2*(Gun base dmg+bullet dmg)+damage gear]*(staff bonus)*(day/weather bonuses)*mab`

COR75/BLM37 (MAB+24)
Corsair's Gun +1 = 42 DMG
Steel Bullet = 70 DMG

### Ice Shot
Observed Damage = **451**
Expected Damage = **277**
floor((2*(42+70)) * 1.24)
floor((2*112) * 1.24)
floor(224 * 1.24)
floor(277.76)

### Adding Corsair's Tricorne
Observed Damage = **457**
Expected Damage = **290**
floor(234 * 1.24)
floor(290.16)

### Thunder Shot, Jupiter's Staff, Corsair's Tricorne, Moldavite Earring, Uggalepih Pendant, /BLM, Lightningsday
Observed Damage = **638**
Expected Damage = **405**
floor(234 * 1.15 * 1.10 * 1.37)
floor(405.5337)

**Comment by VirtuosusFFXI** [comment]
Just an update to this, if anyone wants to take a look at fixing it. Oversight was that it was using `player:getRangedDmg() + player:getAmmoDmg()` as base damage, but it needs to use only `player:getRangedDmg()` as that should already includes ammo. So it is currently counting ammo damage twice, hence the higher than expected numbers. Math checks out.

**Comment by 59blargedy** [comment]
resolved in July 29, 2021 update

**Comment by joercasey** [comment]
Thunder Shot still appears to be double-counting ammo damage. And the Corsair's Tricorne is adding only 5 damage (expected to be 10?)

(Tests on bees outside South Gustaburg, 75COR/37WAR, Lightsday & Darksday)

```
naked (agi=71; cor/war); bandit+1 (dmg:15); bullet (dmg:46)
thunder: 214, 214; (gun+ammo+ammo)*2 = 214
ice: 122, 122; (gun+ammo)*2 = 122
earth: 61 (1/2 resist), 122

naked (agi=71); corsair's (dmg:41); steel (dmg:70)
thunder: 362; (gun+ammo+ammo)*2 = 362
ice: 222; (gun+ammo)*2 = 222
earth: 222

naked, af hat; corsair's (dmg:41); steel (dmg:70)
thunder: 367; (gun+ammo+ammo)*2 + 5 = 367
ice: 227; (gun+ammo)*2 + 5 = 227
earth: 227

full agi (103), af hat; MAB=0; corsair's; steel
thunder: 367
ice: 227
earth: 

full agi (100), af hat; MAB=13 (moldavite, uggy); corsair's; steel
thunder: 414; ((gun+ammo+ammo)*2+5)*1.13 = ((41+70+70)*2+5)*1.13 = 414.71
ice: 256; ((gun+ammo)*2+5)*1.13 = ((41+70)*2+5)*1.13 = 256.51
earth: 256
```

**Comment by 59blargedy** [comment]
yeah looks like we left in ammo for that one, thanks for catching, fixed in next update.
the addl damage from tricorne has competing data, until we get a retail test, going to stay with the 5 that's been there
https://ffxiclopedia.fandom.com/wiki/Corsair%27s_Tricorne
