### ISSUE TITLE
Manticore Family Great Whirlwind

### ISSUE THREAD

**Issue by FariskaEden** [EdenServer/community#4524]
### Checklist

- [X] I have searched for existing issues for issues like this one. The issue has not been posted. (Duplicate reports slow down development.)
- [X] I have provided reproducable steps. (No "as the title says" posts please. Provide reproducable steps even if it seems like a waste of time.)
- [X] I have provided my client version in the details. (type /ver into your game window)

### Details

Currently this TP move will deal damage in a cone from a manticore and the choke DoT effect will be 15 damage per tick. On retail this TP move is single target and the DoT effect looks to be 4 damage per tic.

https://youtu.be/aycgaPRh2eI?t=386 - shows single target damage and DoT damage (8 HP per tic dropped to 4 HP per tic)

version 30181205_0

**Comment by 59blargedy** [comment]
resolved in January 10, 2022 update

**Comment by FariskaEden** [comment]
This move still appears to be conal but should be single target. Does it need a new bug report to cover that?

**Comment by 59blargedy** [comment]
ill need to get another kirin pop/revalidate other manticores. unfortunately just doing it on one mob isn't enough, as they can vary.

**Comment by FariskaEden** [comment]
Kirin's also seems to be single target.
https://i.gyazo.com/680a0b1aeb9b775c933bdd3841a1653d.mp4
