### ISSUE TITLE
Jungle Boogymen issues

### ISSUE THREAD

**Issue by Oyaziiiiiii** [EdenServer/community#490]
1. We were unable to debuff them with slow/para/blind/gravity/bind/silence/dispel/stun/elegy/etc. We got the "no effect" message. They were highly resistant to sleep too but it was land-able.(~50/50 with a merited RDM. BLM was not reliable at all without ES)

2. Astral flow from the SMN was too strong. 1700+ dmg to those unlucky enough to be in range.

https://www.youtube.com/watch?v=SrWOmH7334Y (Shows AF damage, debuffs landing, and susceptibility to sleep)

**Comment by Oyaziiiiiii** [comment]
Based on his other videos I'm pretty sure this one is from retail. No party tp, timestamp, or any other basic addons either. Here's another video I found though from a different source:

https://www.youtube.com/watch?v=6cxHuieH1GI 
:32 slow lands
:37 Astral flow damage on a blm with shellra3, unsure if he has stoneskin

**Comment by godmode** [comment]
Other than Astral Flow this should be working more closely to retail difficulty now. Astral Flow will come on a different ticket along with the other tickets concerning it.

**Comment by kylemorel** [comment]
The Tonberrys still appear very over tuned. They have close to a 90% sleep resist rate against BLM and RDM. Elemental Seal is almost required to land it. Being a light based mob, there should be no trouble sleeping them. They appear heavily resistant to any other form of enfeebles as well. Possible their levels are still set too high for this fight. HQ staves and merits should not be required for a BC60 fight.

2007 wiki page strategy: [https://ffxiclopedia.fandom.com/wiki/Jungle_Boogymen/Strategies?oldid=329893](https://ffxiclopedia.fandom.com/wiki/Jungle_Boogymen/Strategies?oldid=329893l) says the fight is relatively simple, and BLMs can sleep/enfeeble without issue.
