### ISSUE TITLE
Getting exp for aern elemental when killing smn

### ISSUE THREAD

**Issue by falzum** [EdenServer/community#5366]
### Checklist

- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [ ] I have provided my client version in the details. (type /ver into your game window)
- [ ] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Killing Om'aern smn at E-9 in Al'taieu gives exp for the pet when you kill the smn and the pet despawns

Correct behavior should be that you receive no exp from the pet unless you specifically kill it

![image](https://user-images.githubusercontent.com/55296729/201516256-f12168c9-f868-47f0-b51e-394b2993a410.png)

**Comment by E5una** [comment]
Looks like this extends to other beastmen SMNs too

![image](https://user-images.githubusercontent.com/13668758/207700850-df0bff1e-da7a-4fd9-901e-5d8c93284b34.png)

**Comment by 59blargedy** [comment]
this was resolved in a previous update

**Comment by Frozzen907** [comment]
Appears to be still happening~ 

![Image](https://github.com/user-attachments/assets/539d4c68-b4f5-4a92-bb6c-5b9da7c42ffb)
