### ISSUE TITLE
Ranged attacks cannot be interrupted by movement & ranged animation will play even if facing away from a monster.

### ISSUE THREAD

**Issue by Ameraphise** [EdenServer/community#6200]
- [x] I have searched for existing issues for issues like this one. The issue has not been posted.
- [x] I have provided reproducible steps. (No "as the title says" posts please. ***Please try to state facts only, and avoid assumptions/opinions.***)
- [x] I have provided my client version in the details. (type /ver into your game window)
- [x] ***I have provided proof of my claim (era videos, links to era wiki and/or forum posts)*** Lack of proof will slow down fixes and prioritization. Please provide details so that developers' research time is minimized.

### Details

Version 30181205_0

New bugs following today's patch.

-Ranged attacks which are correctly facing a monster when initiated cannot be interrupted by movement. Can be stopped by resting.
-The ranged attack animation incorrectly plays when attempting to ranged attack an enemy while not facing the monster. Does not interrupt melee attacks.  Does not fire a bolt.

See video

https://youtu.be/AC8W58_Q6F8

**Comment by falzum** [comment]
As of the 7/4 maint you can still shoot while running. The not facing the mob aspect is fixed however.

**Comment by falzum** [comment]
I should add that I was using marksmanship on my above post

**Comment by Frozzen907** [comment]
Still happens with all forms of Ranged Attack, also still goes off even if you turn facing the opposite direction. 
Every once in awhile i'll get an interrupt, but 90% of the time your ranged will still go off even if you move/are moving/facing wrong way. 
(Just tested with Throwing, Xbow, Gun & Bow)

**Comment by Ameraphise** [comment]
Did further testing and found that 

- if the player is still facing the monster when the ranged attack should fire it can be interrupted by movement. 
- If the player is not facing the monster when the ranged attack should fire it cannot be interrupted by movement.

Issue with animation playing despite facing wrong direction initially seems fixed
Thanks

**Comment by Frozzen907** [comment]
From testing i did; if you are locked onto the target you can interrupt your ranged attack, anytime else while unlocked it still goes off.

**Comment by 59blargedy** [comment]
resolved by another dev in July 23, 2025 update
