### ISSUE TITLE
Warrior's Double Attacking and Triple Attacking Constantly After Update

### ISSUE THREAD

**Issue by Asgardx** [EdenServer/community#695]
![halgrin_2019 01 07_190434](https://user-images.githubusercontent.com/46469521/50807484-6e436c80-12af-11e9-94f9-f5b38ea14931.png)
![halgrin_2019 01 07_190507](https://user-images.githubusercontent.com/46469521/50807485-6e436c80-12af-11e9-9c01-d5bf16ae5b3a.png)
![halgrin_2019 01 07_190526](https://user-images.githubusercontent.com/46469521/50807486-6e436c80-12af-11e9-821b-94af2cf8fe26.png)
![halgrin_2019 01 07_190542](https://user-images.githubusercontent.com/46469521/50807487-6e436c80-12af-11e9-9b7e-5290b2e01f1f.png)

- Whenever I swing I have a massive increase to my double attack chance. Seems to be damn near 100%. The second swing always does less than 10 damage and occasionally I triple attack. I'm a 33 Warrior  with thf subbed.

**Comment by Sethious** [comment]
i now am double atking every swing i caught his virus, but seriously i am.

**Comment by Sethious** [comment]
Relogging seems to fix the problem as a temp solution, i dont know if it will come back.

**Comment by Caelic** [comment]
Speculation here but possibly it's doing 10% of the damage 100% of the time instead of 100% of the damage 10% of the time? Still pretty game-breaking.

**Comment by Moldran** [comment]
resolved after the final reset last night

**Comment by Aneyus** [comment]
This is still happening as of 11:04AM EST 1/8/19, please reopen this ticket @tectal831 @godmode

**Comment by Hatberg** [comment]
Still happening on SAM/war 57 level synced down to 10. I do 100% double attack with weak hits of 1-5 damage with a Katayama Ichimonji.

**Comment by godmode** [comment]
Are you guys using gearlock addon?

**Comment by godmode** [comment]
If someone picks up this ticket before me. Montijin was about to get a reliable repro. Equip a two handed weapon + strap then switch to a one handed weapon + no offhand and you will get this bug.

**Comment by Asgardx** [comment]
Not using Gearlock.

I have no strap. However, I can say that I did swap to a 1h with no offhand then back. The bug seems to happen on both 1h and 2h weapons but the 1h + no offhand may have been the cause.

**Comment by blagcher** [comment]
I've been exclusively playing SAM since the client update, in either SAM/war or SAM/thf . This means I've been only using Great Katanas and Polearms.

When synced above 30, I've used Brass Grip (DEX+1). 

When synced under 30, I use no strap. Weapons are either Katayama Ichimonji (GKat), Spark Spear (Polearm, no batteries used) or Royal Spearman's Spear (Polearm) or Okanehira (GKat). With all four weapons I've had the issue.

I'm not able to login right now, but my gut feeling is that it's related to syncing down while wearing a strap, which automatically unequips the strap that was too high level. It sounds a lot like @godmode 's comment, because when you equip a 1hander, it automagically unequips straps as well.

Logging out and logging back in did not resolve the issue for me however.

I don't use Gearlock (unless it's somehow enabled in Ashita by default).

**Comment by godmode** [comment]
Thanks, it’s not related to lockstyle being disabled. I enabled and tried to reproduce and the same issue exists. This appears to be something from a recent update.

**Comment by Altnob** [comment]
It should be stated that while you double attack every time with this bug, your base delay becomes double. 

So, essentially it balances itself out, however it's still broken.

**Comment by Catrim** [comment]
https://www.youtube.com/watch?v=9MXYJQjVxeI

**Comment by Siushaga** [comment]
After some testing, I'm confident that this is related to grips even without syncs, though syncing makes it more noticeable since you're changing to lower level grips or unequipping all together from the lower level syncing. 

Issue is temporarily fixed by logging out and logging back in, but then you can reproduce the issue by equipping to a different grip or unequipping your grip. Next fight then on you'll immediately be back to the extremely slow attacks (went up from 8 secs to 15 secs with my GKT between attacks). 

Example:
Logged off with Tachi of Trials with Mythril Grip +1 equipped and logged back to fix the bug.
Swapped grip to Brass Grip +1 and fought an enemy
Delay between attacks doubled and every attack was a double attack
Logged off and logged back on 
Found an enemy and back to normal
Unequipped grip all together and fought an enemy
Back to the slow delay + double attack

So this bug will definitely be more prevalent when going to an exp pt with a level sync and having to swap that slot. You would think that with slower attack delay that having all those double attacks would balance things out so to speak, but it was actually a significant dps loss when I tried it out in party last night.

**Comment by Setz0r** [comment]
just had @Siushaga test for me in person, it is 100% grips causing the issue, either equipping or unequipping one will cause the character to double attack with an extended hit delay.  2nd hit is always low hand2hand level damage.

**Comment by Asgardx** [comment]
I do not own a grip and this happened to me. I'm the original poster and I swapped to a 1h then back and that is what triggered it for me.
