### ISSUE TITLE
DRG quest glitch

### ISSUE THREAD

**Issue by jtkill13** [EdenServer/community#944]
I'm at the end of the spine in Meriphataud Mountains where I trade the Wyvern Egg to the ???.  But I can't find the ???.  Instead its marked Rahal.  So I can't finish the quest.

**Comment by jtkill13** [comment]
![seifer_2019 02 09_201000](https://user-images.githubusercontent.com/47490416/52529488-09f93b80-2ca7-11e9-801e-87fc0f5e7bf2.png)

**Comment by CloudyDesarroi** [comment]
Sounds like an outdated client to me.

**Comment by jtkill13** [comment]
Sorry for sounding noob, but how do I update the client?

**Comment by CloudyDesarroi** [comment]
https://www.edenxi.com/forums/viewtopic.php?f=31&t=506
Just follow the instructions here. It should resolve the problem, but if it doesn't, let us know.

**Comment by jtkill13** [comment]
> https://www.edenxi.com/forums/viewtopic.php?f=31&t=506
> Just follow the instructions here. It should resolve the problem, but if it doesn't, let us know.

I've updated client and I can see the ???.  But I still can't trade the Wyvern Egg for the DRG unlock quest.  Please help.
